// This file was auto-generated by ML.NET Model Builder. 

using PotHoleDetector_Console;
using Microsoft.ML.Data;

// Create single instance of sample data from first line of dataset for model input.
var image = MLImage.CreateFromFile(@"C:\Users\shami\OneDrive\Documentos\GitHub\PotholeSeverity\PotholeSeverity\PotholeSeverity\test\img-105_jpg.rf.3fe9dff3d1631e79ecb480ff403bcb86.jpg");
PotHoleDetector.ModelInput sampleData = new PotHoleDetector.ModelInput()
{
    Image = image,
};
// Make a single prediction on the sample data and print results.
var predictionResult = PotHoleDetector.Predict(sampleData);
Console.WriteLine("\n\nPredicted Boxes:\n");
if (predictionResult.PredictedBoundingBoxes == null)
{
    Console.WriteLine("No Predicted Bounding Boxes");
    return;
}
var boxes =
    predictionResult.PredictedBoundingBoxes.Chunk(4)
        .Select(x => new { XTop = x[0], YTop = x[1], XBottom = x[2], YBottom = x[3] })
        .Zip(predictionResult.Score, (a, b) => new { Box = a, Score = b });

foreach (var item in boxes)
{
    Console.WriteLine($"XTop: {item.Box.XTop},YTop: {item.Box.YTop},XBottom: {item.Box.XBottom},YBottom: {item.Box.YBottom}, Score: {item.Score}");
}

